In [12]:
# Truc huynh

import sklearn
import numpy as np
from sklearn.metrics import pairwise_distances

In [2]:
X = np.array([
    [-3.44, 1 ],
    [-6.48, 5],
    [0.93, -2],
    [0.2, 2],
    [-6.69, 13 ],
    [-5.85, 4],
    [3.0, 0],
    [-0.36, 0],
    [1.68, -3],
    [-0.45, -3]
    
])

np.set_printoptions(precision=2, linewidth=100, floatmode='fixed')
sklearn.metrics.pairwise_distances(X)

array([[ 0.00,  5.02,  5.30,  3.77, 12.43,  3.85,  6.52,  3.24,  6.50,  4.99],
       [ 5.02,  0.00, 10.19,  7.32,  8.00,  1.18, 10.72,  7.90, 11.43, 10.02],
       [ 5.30, 10.19,  0.00,  4.07, 16.82,  9.05,  2.88,  2.38,  1.25,  1.70],
       [ 3.77,  7.32,  4.07,  0.00, 12.98,  6.37,  3.44,  2.08,  5.21,  5.04],
       [12.43,  8.00, 16.82, 12.98,  0.00,  9.04, 16.21, 14.46, 18.06, 17.17],
       [ 3.85,  1.18,  9.05,  6.37,  9.04,  0.00,  9.71,  6.79, 10.28,  8.84],
       [ 6.52, 10.72,  2.88,  3.44, 16.21,  9.71,  0.00,  3.36,  3.28,  4.57],
       [ 3.24,  7.90,  2.38,  2.08, 14.46,  6.79,  3.36,  0.00,  3.63,  3.00],
       [ 6.50, 11.43,  1.25,  5.21, 18.06, 10.28,  3.28,  3.63,  0.00,  2.13],
       [ 4.99, 10.02,  1.70,  5.04, 17.17,  8.84,  4.57,  3.00,  2.13,  0.00]])

In [5]:
# 0 = star
# 1 = spade
y = np.array([
    0,
    1,
    0,
    1,
    0,
    0,
    1,
    1,
    1,
    0
])

In [9]:
#a
from sklearn.neighbors import NearestNeighbors
neigh = NearestNeighbors(n_neighbors=4)
neigh.fit(X)
distances, neighbors = neigh.kneighbors([X[1],X[7]])

#create a nearest neighbor classifier = 4 
#fit the data X to the classifier
#extract the distances and neighbors from kneighbors function
#print the appropriate information

print(neighbors)

[[1 5 0 3]
 [7 3 2 9]]


In [10]:
#b
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import accuracy_score

loo = LeaveOneOut()
errs = []

for train_index, test_index in loo.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    neigh = KNeighborsClassifier(n_neighbors=1)
    neigh.fit(X_train,y_train)
    predict = neigh.predict(X_test)
    acc = accuracy_score(predict, y_test)
    # 1-acc because we want the error rate
    errs.append(1-acc)
    
# Final error rate is 0.7
np.mean(errs)

#create leave one out CV split on X and iterate through all possible splits
#split the X data into test and train data based on indexes from split
#create a Nearest neighbor classifier = 1
#fit the classifier to the X data
#predict the label of the test data
#compute the accuracy of the classification
#compute the error rate = 1-accuracy
#append the error rate to a list

#once you complete iterating through all the different data find the mean of the error



0.7

In [11]:
#c
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score

#create a kfold split = 3
kf = KFold(n_splits=3)
errs = []

for train_index, test_index in kf.split(X):
    print("Train:", train_index)
    print("Test:", test_index)
    print()
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train,y_train)
    predict = neigh.predict(X_test)
    acc = accuracy_score(predict, y_test)
    
    # 1-acc because we want the error rate
    errs.append(1-acc)
    
# Final error rate is 0.69
# Ignore the answer that it says in the document

np.mean(errs)

#iterate through all splits and find the train and test indexes
#split the data into train and text sets based on the indexes
#create a nearest neighbor classifier = 3
#fit the data to the classifier
#predict the label of the test data
#compute the accuracy of the prediction
#compute the error rate = 1-accuracy
#append the error rates to a list
#compute the mean of all error rates

Train: [4 5 6 7 8 9]
Test: [0 1 2 3]

Train: [0 1 2 3 7 8 9]
Test: [4 5 6]

Train: [0 1 2 3 4 5 6]
Test: [7 8 9]



0.5